CC := $(HOME)/Development/Research/gcc.sh/gcc.sh
CFLAGS := -pthread -D_POSIX_C_SOURCE=200112 -static --target=armv7
#CFLAGS := -O3 -pthread -D_POSIX_C_SOURCE=200112
#CFLAGS := -g3 -pthread -D_POSIX_C_SOURCE=200112
#CFLAGS := $(CFLAGS) -Wall -W -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wdisabled-optimization
#CFLAGS := $(CFLAGS) -Wpadded -Winline -Wpointer-arith -Wsign-compare -Wendif-labels
#LDFLAGS := -lm
LDFLAGS := -lm -static -lpthread

# BASEDIR needs to be set to the same directory as this Makefile
# BASEDIR := $(HOME)/Splash-3/codes
BASEDIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))
MACROS := $(BASEDIR)/null_macros/c.m4.null
M4 := m4 -s -Ulen -Uindex

x = *

$(TARGET): $(OBJS) $(BASEDIR)
	mkdir -p $(BASEDIR)
	$(CC) $(OBJS) $(CFLAGS) -o $(TARGET) $(LDFLAGS)

clean:
	rm -rf *.c *.h *.o *.s *.ll *.bc $(TARGET)

.SUFFIXES:
.SUFFIXES:	.o .c .C .h .H

.H.h:
	$(M4) $(MACROS) $*.H > $*.h

.C.c:
	$(M4) $(MACROS) $*.C > $*.c

.c.o:
	$(CC) -c $(CFLAGS) $*.c

.C.o:
	$(M4) $(MACROS) $*.C > $*.c
	$(CC) -c $(CFLAGS) $*.c
